use super::detector::WafType;

pub struct WafSignature {
    pub waf_type: WafType,
    pub headers: Vec<(String, String)>, // (header_name, pattern)
    pub server_patterns: Vec<String>,
    pub cookies: Vec<String>,
    pub body_patterns: Vec<String>,
}

pub fn load_signatures() -> Vec<WafSignature> {
    vec![
        // Cloudflare
        WafSignature {
            waf_type: WafType::Cloudflare,
            headers: vec![
                ("server".to_string(), "cloudflare".to_string()),
                ("cf-ray".to_string(), "".to_string()),
                ("cf-cache-status".to_string(), "".to_string()),
            ],
            server_patterns: vec!["cloudflare".to_string()],
            cookies: vec!["__cfduid".to_string(), "__cf_bm".to_string()],
            body_patterns: vec![
                "cloudflare".to_string(),
                "ray id".to_string(),
                "cloudflare-nginx".to_string(),
                "attention required".to_string(),
            ],
        },
        // Imperva Incapsula
        WafSignature {
            waf_type: WafType::Imperva,
            headers: vec![
                ("x-cdn".to_string(), "incapsula".to_string()),
                ("x-iinfo".to_string(), "".to_string()),
            ],
            server_patterns: vec![],
            cookies: vec![
                "incap_ses_".to_string(),
                "visid_incap_".to_string(),
                "nlbi_".to_string(),
            ],
            body_patterns: vec![
                "incapsula".to_string(),
                "incident id".to_string(),
                "_incapsula_resource".to_string(),
            ],
        },
        // Akamai
        WafSignature {
            waf_type: WafType::Akamai,
            headers: vec![
                ("server".to_string(), "akamaighost".to_string()),
                ("x-akamai-request-id".to_string(), "".to_string()),
                ("akamai-origin-hop".to_string(), "".to_string()),
            ],
            server_patterns: vec!["akamaighost".to_string()],
            cookies: vec!["ak_bmsc".to_string(), "bm_sz".to_string()],
            body_patterns: vec![
                "akamai".to_string(),
                "reference #".to_string(),
                "access denied".to_string(),
            ],
        },
        // F5 BIG-IP
        WafSignature {
            waf_type: WafType::F5BigIP,
            headers: vec![
                ("server".to_string(), "big-ip".to_string()),
                ("x-wa-info".to_string(), "".to_string()),
            ],
            server_patterns: vec!["big-ip".to_string(), "bigip".to_string()],
            cookies: vec![
                "bigipserver".to_string(),
                "f5-".to_string(),
                "ts".to_string(),
            ],
            body_patterns: vec![
                "the requested url was rejected".to_string(),
                "f5 networks".to_string(),
                "bigip".to_string(),
            ],
        },
        // ModSecurity
        WafSignature {
            waf_type: WafType::ModSecurity,
            headers: vec![("server".to_string(), "mod_security".to_string())],
            server_patterns: vec!["mod_security".to_string(), "modsecurity".to_string()],
            cookies: vec![],
            body_patterns: vec![
                "mod_security".to_string(),
                "this error was generated by mod_security".to_string(),
                "modsecurity".to_string(),
            ],
        },
        // AWS WAF
        WafSignature {
            waf_type: WafType::AwsWaf,
            headers: vec![
                ("x-amzn-requestid".to_string(), "".to_string()),
                ("x-amzn-errortype".to_string(), "".to_string()),
                ("x-amz-cf-id".to_string(), "".to_string()),
            ],
            server_patterns: vec!["awselb".to_string(), "amazon".to_string()],
            cookies: vec!["awsalb".to_string(), "awsalbcors".to_string()],
            body_patterns: vec![
                "aws".to_string(),
                "forbidden".to_string(),
                "request blocked".to_string(),
            ],
        },
        // Azure WAF
        WafSignature {
            waf_type: WafType::AzureWaf,
            headers: vec![
                ("x-azure-ref".to_string(), "".to_string()),
                ("x-msedge-ref".to_string(), "".to_string()),
            ],
            server_patterns: vec!["azure".to_string()],
            cookies: vec!["arr".to_string()],
            body_patterns: vec![
                "azure".to_string(),
                "microsoft".to_string(),
                "this request has been blocked".to_string(),
            ],
        },
        // Sucuri
        WafSignature {
            waf_type: WafType::Sucuri,
            headers: vec![
                ("server".to_string(), "sucuri".to_string()),
                ("x-sucuri-id".to_string(), "".to_string()),
                ("x-sucuri-cache".to_string(), "".to_string()),
            ],
            server_patterns: vec!["sucuri".to_string()],
            cookies: vec!["sucuri-".to_string()],
            body_patterns: vec![
                "sucuri".to_string(),
                "cloudproxy".to_string(),
                "access denied - sucuri website firewall".to_string(),
            ],
        },
        // Wordfence
        WafSignature {
            waf_type: WafType::Wordfence,
            headers: vec![],
            server_patterns: vec![],
            cookies: vec!["wfvt_".to_string(), "wordfence".to_string()],
            body_patterns: vec![
                "wordfence".to_string(),
                "generated by wordfence".to_string(),
                "this response was generated by wordfence".to_string(),
            ],
        },
        // Barracuda
        WafSignature {
            waf_type: WafType::Barracuda,
            headers: vec![("server".to_string(), "barracuda".to_string())],
            server_patterns: vec!["barracuda".to_string()],
            cookies: vec!["barra_counter".to_string()],
            body_patterns: vec![
                "barracuda".to_string(),
                "you have been blocked".to_string(),
            ],
        },
        // Fortinet FortiWeb
        WafSignature {
            waf_type: WafType::Fortiweb,
            headers: vec![],
            server_patterns: vec!["fortiweb".to_string()],
            cookies: vec!["fortiweb".to_string()],
            body_patterns: vec![
                "fortinet".to_string(),
                "fortiweb".to_string(),
                "request denied by fortiweb".to_string(),
            ],
        },
        // Wallarm
        WafSignature {
            waf_type: WafType::Wallarm,
            headers: vec![("server".to_string(), "wallarm".to_string())],
            server_patterns: vec!["wallarm".to_string()],
            cookies: vec!["wallarm".to_string()],
            body_patterns: vec![
                "wallarm".to_string(),
                "blocked by wallarm".to_string(),
            ],
        },
    ]
}
